services:
  - type: web
    name: portest-api
    runtime: python
    buildCommand: pip install -e . && echo "=== FILES ===" && ls -la models/ && ls -la data/full_df.csv
    startCommand: python -m api.api
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8000"
    healthCheckPath: /health
